output "dnssec_status" {
  description = "DNSSEC desired status managed by this workspace."
  value       = cloudflare_zone_dnssec.sobok_cc.status
}

output "dnssec_ds" {
  description = "Delegation Signer record generated by Cloudflare."
  value       = cloudflare_zone_dnssec.sobok_cc.ds
}
