---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - imagepolicy.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: chat-config
    literals:
      - NODE_ENV=production
      - PORT=3003
      - APP_ORIGIN=https://sobok.cc
      - APP_POSTGRES_APPLICATION_NAME=sobok-chat
      - APP_NAME=sobok
      - AUTH_TRUSTED_ORIGINS=https://sobok.cc
      - BETTER_AUTH_URL=https://sobok.cc/api/auth
      - PASSKEY_ORIGIN=https://sobok.cc
      - PASSKEY_RP_ID=sobok.cc
