---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-pull/ks.yaml
  - image-automation/ks.yaml
  - web/ks.yaml
  - api/ks.yaml
  - chat/ks.yaml
  - chat-worker/ks.yaml
  - chat-push/ks.yaml
  - billing-worker/ks.yaml
